### PR TITLE
Upgrade module to Terraform 0.12

### LINKED ISSUE #27: Request: Terraform 0.12 support
Terraform 0.12 has recently been released, which uses a different syntax for its code. Luckily terraform provides a tool for upgrading the code, so it should be easily done.

### PR DESCRIPTION
**Pull request by bflugon**
Fixes #27

### CODE REVIEW

**Comment by alexsn** [comment]
Is this a dead project? Why is this pull request not being reviewed?

**Comment by core-tec** [comment]
It would be very useful to get this reviewed and merged.

**Comment by antonbabenko** [comment]
@alexsn This project is not dead, but the amount of work in all [terraform-aws-modules](https://github.com/terraform-aws-modules) and [terraform-community-modules](https://github.com/terraform-community-modules) is just too much for me to handle in a timely manner.

**Comment by aruncentrica** [comment]
thanks @bflugon , I tested with 0.12 and it works

**Comment by aruncentrica** [comment]
@antonbabenko  It would be very useful to get this reviewed and merged.

**Comment by antonbabenko** [comment]
Thanks @bflugon for the pull-request!

[v1.0.0](https://github.com/terraform-community-modules/tf_aws_elasticsearch/releases/v1.0.0) has been just released, it has support for Terraform 0.12.

Use previous versions (`~> 0.0`) if you are using Terraform 0.11 or earlier.

**Pull request closed without merging**
